questions:
    min-players: 3
    answers-accepted: 1
    timeout: 10
    interval: 30
    hide-answer: false
    sounds:
        asked: NONE
        answered-right: NONE
        answered-wrong: NONE
        ended: NONE

open-trivia-db:
    enabled: false
    default-rewards:
        - give DIAMOND 1

database:
    use-sqlite: true
    hostname: localhost
    port: 3306
    database: default
    username: root
    password: password

misc:
    answer-prefix: '?'
    disabled-worlds:
    #    - your_world_here
    debug: false