questions:
    min-players: 3
    answers-accepted: 1
    timeout: 10
    interval: 30
    sounds:
        asked: NONE
        answered-right: NONE
        answered-wrong: NONE
        ended: NONE

open-trivia-db:
    enabled: false
    default-rewards:
        - give DIAMOND 1

misc:
    answer-prefix: '?'