name: FunQuiz
version: 2.0.0
main: me.m0dex.funquiz.FunQuiz
author: M0dEx
softdepend: [Vault]
commands:
    funquiz:
        description: Main command.
        usage: /fq
        aliases: fq
    questions:
        description: Question control.
        usage: /questions
        aliases: q