name: FunQuiz
version: v2.0.0-alpha-4
main: me.m0dex.funquiz.FunQuiz
author: M0dEx
commands:
    funquiz:
        description: Main command.
        usage: /fq
        aliases: fq
    questions:
        description: Question control.
        usage: /questions
        aliases: q